stages:
  - test
  - build
  - deploy


test:
  stage: test
  services:
    - python:3.6
    - postgres:alpine
  variables:
    POSTGRES_DB: custom_db
    POSTGRES_USER: custom_user
    POSTGRES_PASSWORD: custom_pass
  script:
    - export DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@postgres:5432/$POSTGRES_DB
    - apt-get update -qy
    - apt-get install -y python-dev python-pip
    - pip install -r requirements.txt
    - python manage.py test

build:
  stage: build
  script: echo "Test build"

deploy:
  stage: deploy
  script: echo "Test deploy"