image: python:3.6

stages:
  - test
  - build
  - deploy

variables:
  MYVAR: $'import sys\n
  if \'test\' in sys.argv:\n
    DATABASES = {\n
        \'default\': {\'ENGINE\': \'django.db.backends.sqlite3\'}\n
    }'

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - apt-get install -y locales locales-all
    - apt-get install sqlite3
    - pip install -r requirements.txt
    - echo -e $MYVAR > refactor_oc/refactor_oc/local_settings.py
    - cat refactor_oc/refactor_oc/local_settings.py
    - cd refactor_oc/
    - python manage.py test

build:
  stage: build
  when: manual
  script: echo "Test build"

deploy:
  stage: deploy
  when: manual
  script: echo "Test deploy"