image: python:3.6

stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
    - mysql:latest

  variables:
    MYSQL_DATABASE: database
    MYSQL_ROOT_PASSWORD: password

  script:
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip install -r requirements.txt
    - cd refactor_oc/
    - python manage.py test

build:
  stage: build
  script: echo "Test build"

deploy:
  stage: deploy
  script: echo "Test deploy"