image: python:3.6

stages:
  - test
  - build
  - deploy

test:
  stage: test
  when: manual

  variables:
    TEST_SETTINGS: "import sys if 'test' in sys.argv: DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3'}}"


  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - apt-get install -y locales locales-all
    - apt-get install sqlite3
    - pip install -r requirements.txt
    - cd refactor_oc/refactor_oc/ && echo $TEST_SETTINGS > local_settings.py
    - cd ../
    - python manage.py test

build:
  stage: build
  when: manual
  script: echo "Test build"

deploy:
  stage: deploy
  when: manual
  script: echo "Test deploy"