image: python:3.6

stages:
  - test
  - build
  - deploy



before_script:
  - touch refactor_oc/refactor_oc/local_settings.py
  - cat > refactor_oc/refactor_oc/local_settings.py <<EOF
  - $MYVAR
  - EOF

test:
  stage: test
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - apt-get install -y locales locales-all
    - apt-get install sqlite3
    - pip install -r requirements.txt
    - cat refactor_oc/refactor_oc/local_settings.py
    - cd refactor_oc/
    - python manage.py test

build:
  stage: build
  when: manual
  script: echo "Test build"

deploy:
  stage: deploy
  when: manual
  script: echo "Test deploy"