image: python:3.6

stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
    - mysql:latest

  variables:
    MYSQL_DATABASE: cinema2
    MYSQL_ROOT_PASSWORD: password

  connect:
    image: mysql
    script:
      - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"

  script:
#    - export DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@3306:3306/$MYSQL_DATABASE
#    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - apt-get install -y locales locales-all
    - pip install -r requirements.txt
    - cd refactor_oc/
    - python manage.py test

build:
  stage: build
  script: echo "Test build"

deploy:
  stage: deploy
  script: echo "Test deploy"