image: python:3.6

stages:
  - test
  - build
  - deploy

test:
  stage: test
  services:
    - mysql:latest

  variables:
    MYSQL_DATABASE: cinema2
    MYSQL_ROOT_PASSWORD: password

  script:
    - export DATABASE_URL=mysql://root:$MYSQL_ROOT_PASSWORD@mysql:3306/$MYSQL_DATABASE
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip
    - pip install -r requirements.txt
    - pip install -y sqlite3
    - cd refactor_oc/
    - python manage.py test

build:
  stage: build
  script: echo "Test build"

deploy:
  stage: deploy
  script: echo "Test deploy"