# Generated by Django 2.2 on 2019-05-31 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestseller',
            options={'verbose_name': 'bestseller', 'verbose_name_plural': 'bestsellers'},
        ),
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'bookmark', 'verbose_name_plural': 'bookmarks'},
        ),
        migrations.AlterModelOptions(
            name='check',
            options={'verbose_name': 'check', 'verbose_name_plural': 'checks'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterModelOptions(
            name='fileslost',
            options={'verbose_name': 'filelost', 'verbose_name_plural': 'fileslost'},
        ),
        migrations.AlterModelOptions(
            name='filesstat',
            options={'verbose_name': 'files_stat', 'verbose_name_plural': 'files_stats'},
        ),
        migrations.AlterModelOptions(
            name='filestask',
            options={'verbose_name': 'files_task', 'verbose_name_plural': 'files_tasks'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'genre', 'verbose_name_plural': 'genres'},
        ),
        migrations.AlterModelOptions(
            name='hit',
            options={'verbose_name': 'hit', 'verbose_name_plural': 'hits'},
        ),
        migrations.AlterModelOptions(
            name='incoming',
            options={'verbose_name': 'incoming', 'verbose_name_plural': 'incomings'},
        ),
        migrations.AlterModelOptions(
            name='languagesproto',
            options={'verbose_name': 'languages_proto', 'verbose_name_plural': 'languages_protos'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'log', 'verbose_name_plural': 'logs'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='ocuser',
            options={'verbose_name': 'ocuser', 'verbose_name_plural': 'ocusers'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'participant', 'verbose_name_plural': 'participants'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'rating', 'verbose_name_plural': 'ratings'},
        ),
        migrations.AlterModelOptions(
            name='registry',
            options={'verbose_name': 'registry', 'verbose_name_plural': 'registries'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'role', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='searchtrigram',
            options={'verbose_name': 'search_trigram', 'verbose_name_plural': 'search_trigrams'},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'selection', 'verbose_name_plural': 'selections'},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'suggestion', 'verbose_name_plural': 'suggestions'},
        ),
        migrations.AlterModelOptions(
            name='suggestioncache',
            options={'verbose_name': 'suggestion_cache', 'verbose_name_plural': 'suggestion_cache'},
        ),
        migrations.AddField(
            model_name='comment',
            name='to_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='webapp.Comment'),
        ),
        migrations.AlterField(
            model_name='ocuser',
            name='login',
            field=models.CharField(max_length=32, unique=True, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='ocuser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
    ]
